info:
  contact: {}
  description: '---'
  title: API Пользователи и авторизация
  version: "1.0"
paths:
  /api/user/{id}:
    get:
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: Get User by ID
      tags:
      - user
swagger: "2.0"
